#include "codegen.h"
#include "parser.h"
#include "typecheck.h"
#include "specialize.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char *read_file(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc((size_t)size + 1);
    if (!buf) { fclose(f); return NULL; }
    fread(buf, 1, (size_t)size, f);
    buf[size] = '\0';
    fclose(f);
    return buf;
}

bool codegen_emit_c(const IrModule *m, const char *out_path) {
    if (!m || !out_path) return false;

    FILE *f = fopen(out_path, "wb");
    if (!f) return false;

    bool classical = m->all_classical;

    fprintf(f, "/* Auto-generated by Quenti codegen — do not edit */\n");
    fprintf(f, "/* specialization: %s */\n", classical ? "all_classical" : "with_karu_runtime");
    fprintf(f, "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <math.h>\n");
    if (!classical)
        fprintf(f, "#include \"runtime.h\"\n#include \"distribution.h\"\n#include \"collapse.h\"\n");
    fprintf(f, "\n");

    fprintf(f, "typedef enum {\n");
    fprintf(f, "  IR_NOP=0, IR_CONST_I, IR_CONST_F, IR_CONST_S, IR_CONST_B,\n");
    fprintf(f, "  IR_LOAD, IR_STORE, IR_ADD, IR_SUB, IR_MUL, IR_DIV,\n");
    fprintf(f, "  IR_EQ, IR_NEQ, IR_LT, IR_GT, IR_LTE, IR_GTE, IR_NEG,\n");
    fprintf(f, "  IR_JMP, IR_JMP_IF, IR_JMP_IF_NOT, IR_PRINT, IR_POP, IR_CALL, IR_RET,\n");
    fprintf(f, "  IR_KARU_SUPER, IR_KARU_AND, IR_KARU_OR, IR_KARU_NOT, IR_MEASURE,\n");
    fprintf(f, "  IR_P_NORMAL, IR_P_UNIFORM, IR_P_DISCRETE, IR_FORK_IF, IR_RUNTIME_CFG, IR_HALT\n");
    fprintf(f, "} IrOpcode;\n\n");

    fprintf(f, "typedef struct { IrOpcode op; int operand; int aux; double fimm; } IrInst;\n\n");

    fprintf(f, "static const char *gen_strings[] = {\n");
    for (size_t i = 0; i < m->string_count; i++)
        fprintf(f, "  \"%s\",\n", m->strings[i] ? m->strings[i] : "");
    if (m->string_count == 0)
        fprintf(f, "  \"\",\n");
    fprintf(f, "};\n\n");

    fprintf(f, "static const IrInst gen_code[] = {\n");
    for (size_t i = 0; i < m->count; i++) {
        const IrInst *in = &m->code[i];
        fprintf(f, "  { %d, %d, %d, %g },\n",
                (int)in->op, in->operand, in->aux, in->fimm);
    }
    fprintf(f, "};\n\n");

    fprintf(f, "static int gen_func_entry[] = { ");
    if (m->func_count == 0) fprintf(f, "0");
    for (size_t i = 0; i < m->func_count; i++)
        fprintf(f, "%d%s", m->funcs[i].entry_ip, (i + 1 < m->func_count) ? ", " : "");
    fprintf(f, " };\n\n");

    size_t nfunc = m->func_count ? m->func_count : 1;
    fprintf(f, "static int gen_param_slot[%zu][8] = {\n", nfunc);
    for (size_t fi = 0; fi < nfunc; fi++) {
        fprintf(f, "  { ");
        for (int p = 0; p < 8; p++) {
            if (fi < m->func_count && p < m->funcs[fi].arity)
                fprintf(f, "%d, ", m->funcs[fi].param_slots[p]);
            else
                fprintf(f, "-1, ");
        }
        fprintf(f, "},\n");
    }
    fprintf(f, "};\n\n");

    fprintf(f, "typedef enum { GT_INT, GT_FLOAT, GT_STR, GT_BOOL, GT_VOID } GTag;\n");
    fprintf(f, "typedef struct { GTag tag; union { int i; double f; char *s; int b; } u; } GV;\n\n");

    fprintf(f, "static GV g_locals[512];\n");
    fprintf(f, "static GV g_stack[1024];\n");
    fprintf(f, "static int g_sp;\n\n");

    fprintf(f, "static void gv_free(GV *v) {\n");
    fprintf(f, "  if (!v) return;\n");
    fprintf(f, "  if (v->tag == GT_STR) free(v->u.s);\n");
    fprintf(f, "  v->tag = GT_VOID;\n");
    fprintf(f, "}\n\n");

    if (classical) {
        /* Pure classical executor — no QuantiRuntime / libquanti */
        fprintf(f, "static int gen_run(void) {\n");
        fprintf(f, "  size_t ip = 0, ret[256]; int ret_sp = 0;\n");
        fprintf(f, "  g_sp = 0;\n");
        fprintf(f, "  memset(g_locals, 0, sizeof(g_locals));\n");
        fprintf(f, "  while (ip < sizeof(gen_code)/sizeof(gen_code[0])) {\n");
        fprintf(f, "    IrInst in = gen_code[ip++];\n");
        fprintf(f, "    switch (in.op) {\n");
        fprintf(f, "    case IR_NOP: break;\n");
        fprintf(f, "    case IR_POP: if(g_sp>0){g_sp--; gv_free(&g_stack[g_sp]);} break;\n");
        fprintf(f, "    case IR_CONST_I: g_stack[g_sp++] = (GV){GT_INT,{.i=in.operand}}; break;\n");
        fprintf(f, "    case IR_CONST_F: g_stack[g_sp++] = (GV){GT_FLOAT,{.f=in.fimm}}; break;\n");
        fprintf(f, "    case IR_CONST_S: g_stack[g_sp++] = (GV){GT_STR,{.s=strdup(gen_strings[in.operand])}}; break;\n");
        fprintf(f, "    case IR_CONST_B: g_stack[g_sp++] = (GV){GT_BOOL,{.b=in.operand}}; break;\n");
        fprintf(f, "    case IR_LOAD: {\n");
        fprintf(f, "      GV *L=&g_locals[in.operand];\n");
        fprintf(f, "      if(L->tag==GT_STR) g_stack[g_sp++]=(GV){GT_STR,{.s=strdup(L->u.s?L->u.s:\"\")}};\n");
        fprintf(f, "      else g_stack[g_sp++]=*L;\n");
        fprintf(f, "      break; }\n");
        fprintf(f, "    case IR_STORE: gv_free(&g_locals[in.operand]); g_locals[in.operand]=g_stack[--g_sp]; break;\n");
        fprintf(f, "    case IR_ADD: case IR_SUB: case IR_MUL: case IR_DIV:\n");
        fprintf(f, "    case IR_EQ: case IR_NEQ: case IR_LT: case IR_GT: case IR_LTE: case IR_GTE: {\n");
        fprintf(f, "      GV b=g_stack[--g_sp], a=g_stack[--g_sp];\n");
        fprintf(f, "      if (a.tag==GT_FLOAT || b.tag==GT_FLOAT) {\n");
        fprintf(f, "        double l=(a.tag==GT_FLOAT)?a.u.f:(double)a.u.i;\n");
        fprintf(f, "        double r=(b.tag==GT_FLOAT)?b.u.f:(double)b.u.i; GV o={GT_FLOAT,{.f=0}};\n");
        fprintf(f, "        if(in.op==IR_ADD) o.u.f=l+r; else if(in.op==IR_SUB) o.u.f=l-r;\n");
        fprintf(f, "        else if(in.op==IR_MUL) o.u.f=l*r; else if(in.op==IR_DIV) o.u.f=l/r;\n");
        fprintf(f, "        else { o.tag=GT_BOOL; if(in.op==IR_EQ) o.u.b=fabs(l-r)<1e-9; else if(in.op==IR_NEQ) o.u.b=fabs(l-r)>=1e-9;\n");
        fprintf(f, "          else if(in.op==IR_LT) o.u.b=l<r; else if(in.op==IR_GT) o.u.b=l>r;\n");
        fprintf(f, "          else if(in.op==IR_LTE) o.u.b=l<=r; else o.u.b=l>=r; }\n");
        fprintf(f, "        g_stack[g_sp++]=o;\n");
        fprintf(f, "      } else {\n");
        fprintf(f, "        int l=a.u.i, r=b.u.i; GV o={GT_INT,{.i=0}};\n");
        fprintf(f, "        if(in.op==IR_ADD) o.u.i=l+r; else if(in.op==IR_SUB) o.u.i=l-r;\n");
        fprintf(f, "        else if(in.op==IR_MUL) o.u.i=l*r; else if(in.op==IR_DIV) o.u.i=r?l/r:0;\n");
        fprintf(f, "        else { o.tag=GT_BOOL; if(in.op==IR_EQ) o.u.b=l==r; else if(in.op==IR_NEQ) o.u.b=l!=r;\n");
        fprintf(f, "          else if(in.op==IR_LT) o.u.b=l<r; else if(in.op==IR_GT) o.u.b=l>r;\n");
        fprintf(f, "          else if(in.op==IR_LTE) o.u.b=l<=r; else o.u.b=l>=r; }\n");
        fprintf(f, "        g_stack[g_sp++]=o;\n");
        fprintf(f, "      } break; }\n");
        fprintf(f, "    case IR_NEG: { GV a=g_stack[--g_sp]; if(a.tag==GT_FLOAT) a.u.f=-a.u.f; else a.u.i=-a.u.i; g_stack[g_sp++]=a; break; }\n");
        fprintf(f, "    case IR_PRINT: { GV v=g_stack[--g_sp];\n");
        fprintf(f, "      if(v.tag==GT_INT) printf(\"%%d\\n\",v.u.i); else if(v.tag==GT_FLOAT) printf(\"%%g\\n\",v.u.f);\n");
        fprintf(f, "      else if(v.tag==GT_STR) printf(\"%%s\\n\",v.u.s?v.u.s:\"\");\n");
        fprintf(f, "      else if(v.tag==GT_BOOL) printf(\"%%s\\n\",v.u.b?\"true\":\"false\");\n");
        fprintf(f, "      gv_free(&v); break; }\n");
        fprintf(f, "    case IR_JMP: ip=(size_t)in.operand; break;\n");
        fprintf(f, "    case IR_JMP_IF: case IR_JMP_IF_NOT: { GV c=g_stack[--g_sp]; int t=0;\n");
        fprintf(f, "      if(c.tag==GT_INT) t=c.u.i!=0; else if(c.tag==GT_BOOL) t=c.u.b;\n");
        fprintf(f, "      gv_free(&c); if(in.op==IR_JMP_IF ? t : !t) ip=(size_t)in.operand; break; }\n");
        fprintf(f, "    case IR_CALL: { int fi=in.operand, argc=in.aux;\n");
        fprintf(f, "      for(int a=argc-1;a>=0;a--){ gv_free(&g_locals[gen_param_slot[fi][a]]); g_locals[gen_param_slot[fi][a]]=g_stack[--g_sp]; }\n");
        fprintf(f, "      ret[ret_sp++]=ip; ip=(size_t)gen_func_entry[fi]; break; }\n");
        fprintf(f, "    case IR_RET: { if(ret_sp) ip=ret[--ret_sp]; else ip=sizeof(gen_code)/sizeof(gen_code[0]); break; }\n");
        fprintf(f, "    case IR_HALT: ip=sizeof(gen_code)/sizeof(gen_code[0]); break;\n");
        fprintf(f, "    default: break;\n");
        fprintf(f, "    }\n  }\n  return 0;\n}\n\n");
        fprintf(f, "int main(void) { return gen_run(); }\n");
    } else {
        /* Full executor with runtime — reuse previous complete switch via include of logic */
        /* Emit karu-capable GV and gen_run(rt) */
        fclose(f);
        /* Fall through: rewrite file with full path by reopening */
        f = fopen(out_path, "wb");
        if (!f) return false;
        fprintf(f, "/* Auto-generated by Quenti codegen — with_karu_runtime */\n");
        fprintf(f, "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <math.h>\n");
        fprintf(f, "#include \"runtime.h\"\n#include \"distribution.h\"\n#include \"collapse.h\"\n\n");
        fprintf(f, "typedef enum {\n");
        fprintf(f, "  IR_NOP=0, IR_CONST_I, IR_CONST_F, IR_CONST_S, IR_CONST_B,\n");
        fprintf(f, "  IR_LOAD, IR_STORE, IR_ADD, IR_SUB, IR_MUL, IR_DIV,\n");
        fprintf(f, "  IR_EQ, IR_NEQ, IR_LT, IR_GT, IR_LTE, IR_GTE, IR_NEG,\n");
        fprintf(f, "  IR_JMP, IR_JMP_IF, IR_JMP_IF_NOT, IR_PRINT, IR_POP, IR_CALL, IR_RET,\n");
        fprintf(f, "  IR_KARU_SUPER, IR_KARU_AND, IR_KARU_OR, IR_KARU_NOT, IR_MEASURE,\n");
        fprintf(f, "  IR_P_NORMAL, IR_P_UNIFORM, IR_P_DISCRETE, IR_FORK_IF, IR_RUNTIME_CFG, IR_HALT\n");
        fprintf(f, "} IrOpcode;\n");
        fprintf(f, "typedef struct { IrOpcode op; int operand; int aux; double fimm; } IrInst;\n");
        fprintf(f, "static const char *gen_strings[] = {\n");
        for (size_t i = 0; i < m->string_count; i++)
            fprintf(f, "  \"%s\",\n", m->strings[i] ? m->strings[i] : "");
        if (m->string_count == 0) fprintf(f, "  \"\",\n");
        fprintf(f, "};\n");
        fprintf(f, "static const IrInst gen_code[] = {\n");
        for (size_t i = 0; i < m->count; i++) {
            const IrInst *in = &m->code[i];
            fprintf(f, "  { %d, %d, %d, %g },\n", (int)in->op, in->operand, in->aux, in->fimm);
        }
        fprintf(f, "};\n");
        fprintf(f, "static int gen_func_entry[] = { ");
        if (m->func_count == 0) fprintf(f, "0");
        for (size_t i = 0; i < m->func_count; i++)
            fprintf(f, "%d%s", m->funcs[i].entry_ip, (i + 1 < m->func_count) ? ", " : "");
        fprintf(f, " };\n");
        fprintf(f, "static int gen_param_slot[%zu][8] = {\n", nfunc);
        for (size_t fi = 0; fi < nfunc; fi++) {
            fprintf(f, "  { ");
            for (int p = 0; p < 8; p++) {
                if (fi < m->func_count && p < m->funcs[fi].arity)
                    fprintf(f, "%d, ", m->funcs[fi].param_slots[p]);
                else
                    fprintf(f, "-1, ");
            }
            fprintf(f, "},\n");
        }
        fprintf(f, "};\n");
        fprintf(f, "typedef enum { GT_INT, GT_FLOAT, GT_STR, GT_BOOL, GT_KARU, GT_VOID } GTag;\n");
        fprintf(f, "typedef struct { GTag tag; union { int i; double f; char *s; int b; KaruByte k; } u; } GV;\n");
        fprintf(f, "static GV g_locals[512]; static GV g_stack[1024]; static int g_sp;\n");
        fprintf(f, "static void gv_free(GV *v){ if(!v)return; if(v->tag==GT_STR)free(v->u.s); if(v->tag==GT_KARU)karu_free(&v->u.k); v->tag=GT_VOID; }\n");
        fprintf(f, "static int gen_run(QuantiRuntime *rt){\n");
        fprintf(f, " size_t ip=0,ret[256]; int ret_sp=0; g_sp=0; memset(g_locals,0,sizeof(g_locals));\n");
        fprintf(f, " while(ip<sizeof(gen_code)/sizeof(gen_code[0])){\n");
        fprintf(f, "  IrInst in=gen_code[ip++]; switch(in.op){\n");
        fprintf(f, "  case IR_NOP: break;\n");
        fprintf(f, "  case IR_POP: if(g_sp>0){g_sp--; gv_free(&g_stack[g_sp]);} break;\n");
        fprintf(f, "  case IR_CONST_I: g_stack[g_sp++]=(GV){GT_INT,{.i=in.operand}}; break;\n");
        fprintf(f, "  case IR_CONST_F: g_stack[g_sp++]=(GV){GT_FLOAT,{.f=in.fimm}}; break;\n");
        fprintf(f, "  case IR_CONST_S: g_stack[g_sp++]=(GV){GT_STR,{.s=strdup(gen_strings[in.operand])}}; break;\n");
        fprintf(f, "  case IR_CONST_B: g_stack[g_sp++]=(GV){GT_BOOL,{.b=in.operand}}; break;\n");
        fprintf(f, "  case IR_LOAD:{ GV *L=&g_locals[in.operand];\n");
        fprintf(f, "    if(L->tag==GT_STR) g_stack[g_sp++]=(GV){GT_STR,{.s=strdup(L->u.s?L->u.s:\"\")}};\n");
        fprintf(f, "    else if(L->tag==GT_KARU) g_stack[g_sp++]=(GV){GT_KARU,{.k=karu_clone(L->u.k)}};\n");
        fprintf(f, "    else g_stack[g_sp++]=*L;\n");
        fprintf(f, "    break;}\n");
        fprintf(f, "  case IR_STORE: gv_free(&g_locals[in.operand]); g_locals[in.operand]=g_stack[--g_sp]; break;\n");
        fprintf(f, "  case IR_ADD: case IR_SUB: case IR_MUL: case IR_DIV:\n");
        fprintf(f, "  case IR_EQ: case IR_NEQ: case IR_LT: case IR_GT: case IR_LTE: case IR_GTE:{\n");
        fprintf(f, "    GV b=g_stack[--g_sp],a=g_stack[--g_sp];\n");
        fprintf(f, "    if(a.tag==GT_FLOAT||b.tag==GT_FLOAT){ double l=(a.tag==GT_FLOAT)?a.u.f:(double)a.u.i; double r=(b.tag==GT_FLOAT)?b.u.f:(double)b.u.i; GV o={GT_FLOAT,{.f=0}};\n");
        fprintf(f, "      if(in.op==IR_ADD)o.u.f=l+r; else if(in.op==IR_SUB)o.u.f=l-r; else if(in.op==IR_MUL)o.u.f=l*r; else if(in.op==IR_DIV)o.u.f=l/r;\n");
        fprintf(f, "      else{o.tag=GT_BOOL; if(in.op==IR_EQ)o.u.b=fabs(l-r)<1e-9; else if(in.op==IR_NEQ)o.u.b=fabs(l-r)>=1e-9; else if(in.op==IR_LT)o.u.b=l<r; else if(in.op==IR_GT)o.u.b=l>r; else if(in.op==IR_LTE)o.u.b=l<=r; else o.u.b=l>=r;}\n");
        fprintf(f, "      g_stack[g_sp++]=o;\n");
        fprintf(f, "    } else { int l=a.u.i,r=b.u.i; GV o={GT_INT,{.i=0}};\n");
        fprintf(f, "      if(in.op==IR_ADD)o.u.i=l+r; else if(in.op==IR_SUB)o.u.i=l-r; else if(in.op==IR_MUL)o.u.i=l*r; else if(in.op==IR_DIV)o.u.i=r?l/r:0;\n");
        fprintf(f, "      else{o.tag=GT_BOOL; if(in.op==IR_EQ)o.u.b=l==r; else if(in.op==IR_NEQ)o.u.b=l!=r; else if(in.op==IR_LT)o.u.b=l<r; else if(in.op==IR_GT)o.u.b=l>r; else if(in.op==IR_LTE)o.u.b=l<=r; else o.u.b=l>=r;}\n");
        fprintf(f, "      g_stack[g_sp++]=o;} break;}\n");
        fprintf(f, "  case IR_NEG:{ GV a=g_stack[--g_sp]; if(a.tag==GT_FLOAT)a.u.f=-a.u.f; else a.u.i=-a.u.i; g_stack[g_sp++]=a; break;}\n");
        fprintf(f, "  case IR_PRINT:{ GV v=g_stack[--g_sp];\n");
        fprintf(f, "    if(v.tag==GT_KARU){ if(v.u.k.state==KARU_PROB&&v.u.k.dist){const char *lb=dist_map_label(v.u.k.dist); if(lb){printf(\"%%s\\n\",lb); gv_free(&v); break;}}\n");
        fprintf(f, "      if(v.u.k.state==KARU_SUPER||v.u.k.state==KARU_PROB||v.u.k.state==KARU_UNDEF){ KaruByte c=quanti_measure(rt,v.u.k,COLLAPSE_MAP); printf(\"%%d\\n\",c.state==KARU_TRUE?1:0); karu_free(&c);}\n");
        fprintf(f, "      else printf(\"%%d\\n\",v.u.k.state==KARU_TRUE?1:0);\n");
        fprintf(f, "    } else if(v.tag==GT_INT) printf(\"%%d\\n\",v.u.i); else if(v.tag==GT_FLOAT) printf(\"%%g\\n\",v.u.f);\n");
        fprintf(f, "    else if(v.tag==GT_STR) printf(\"%%s\\n\",v.u.s?v.u.s:\"\"); else if(v.tag==GT_BOOL) printf(\"%%s\\n\",v.u.b?\"true\":\"false\");\n");
        fprintf(f, "    gv_free(&v); break;}\n");
        fprintf(f, "  case IR_JMP: ip=(size_t)in.operand; break;\n");
        fprintf(f, "  case IR_JMP_IF: case IR_JMP_IF_NOT:{ GV c=g_stack[--g_sp]; int t=0;\n");
        fprintf(f, "    if(c.tag==GT_INT)t=c.u.i!=0; else if(c.tag==GT_BOOL)t=c.u.b; else if(c.tag==GT_KARU)t=(c.u.k.state==KARU_TRUE);\n");
        fprintf(f, "    gv_free(&c); if(in.op==IR_JMP_IF?t:!t) ip=(size_t)in.operand; break;}\n");
        fprintf(f, "  case IR_CALL:{ int fi=in.operand,argc=in.aux;\n");
        fprintf(f, "    for(int a=argc-1;a>=0;a--){gv_free(&g_locals[gen_param_slot[fi][a]]); g_locals[gen_param_slot[fi][a]]=g_stack[--g_sp];}\n");
        fprintf(f, "    ret[ret_sp++]=ip; ip=(size_t)gen_func_entry[fi]; break;}\n");
        fprintf(f, "  case IR_RET: ip=ret_sp?ret[--ret_sp]:sizeof(gen_code)/sizeof(gen_code[0]); break;\n");
        fprintf(f, "  case IR_KARU_SUPER: g_stack[g_sp++]=(GV){GT_KARU,{.k=quanti_superposition(rt)}}; break;\n");
        fprintf(f, "  case IR_KARU_AND:{ GV b=g_stack[--g_sp],a=g_stack[--g_sp]; KaruByte ka=(a.tag==GT_KARU)?a.u.k:(a.u.i?karu_true():karu_false()); KaruByte kb=(b.tag==GT_KARU)?b.u.k:(b.u.i?karu_true():karu_false()); gv_free(&a);gv_free(&b); g_stack[g_sp++]=(GV){GT_KARU,{.k=quanti_and(rt,ka,kb)}}; break;}\n");
        fprintf(f, "  case IR_KARU_OR:{ GV b=g_stack[--g_sp],a=g_stack[--g_sp]; KaruByte ka=(a.tag==GT_KARU)?a.u.k:(a.u.i?karu_true():karu_false()); KaruByte kb=(b.tag==GT_KARU)?b.u.k:(b.u.i?karu_true():karu_false()); gv_free(&a);gv_free(&b); g_stack[g_sp++]=(GV){GT_KARU,{.k=quanti_or(rt,ka,kb)}}; break;}\n");
        fprintf(f, "  case IR_KARU_NOT:{ GV a=g_stack[--g_sp]; KaruByte ka=(a.tag==GT_KARU)?a.u.k:(a.u.i?karu_true():karu_false()); gv_free(&a); g_stack[g_sp++]=(GV){GT_KARU,{.k=quanti_not(rt,ka)}}; break;}\n");
        fprintf(f, "  case IR_MEASURE:{ GV a=g_stack[--g_sp]; CollapseMode mode=COLLAPSE_MAP; if(in.operand==1)mode=COLLAPSE_SAMPLE; else if(in.operand==2)mode=COLLAPSE_FIRST;\n");
        fprintf(f, "    if(a.tag==GT_KARU&&mode==COLLAPSE_MAP&&a.u.k.state==KARU_PROB&&a.u.k.dist){ const char *lb=dist_map_label(a.u.k.dist); if(lb){ g_stack[g_sp++]=(GV){GT_STR,{.s=strdup(lb)}}; gv_free(&a); break;}}\n");
        fprintf(f, "    KaruByte c=quanti_measure(rt,a.u.k,mode); gv_free(&a); g_stack[g_sp++]=(GV){GT_INT,{.i=(c.state==KARU_TRUE)?1:0}}; karu_free(&c); break;}\n");
        fprintf(f, "  case IR_P_NORMAL:{ GV s=g_stack[--g_sp],mn=g_stack[--g_sp]; double mean=(mn.tag==GT_FLOAT)?mn.u.f:(double)mn.u.i; double sd=(s.tag==GT_FLOAT)?s.u.f:(double)s.u.i; g_stack[g_sp++]=(GV){GT_KARU,{.k=quanti_prob(rt,dist_normal(mean,sd))}}; break;}\n");
        fprintf(f, "  case IR_P_UNIFORM:{ GV mx=g_stack[--g_sp],mn=g_stack[--g_sp]; double a=(mn.tag==GT_FLOAT)?mn.u.f:(double)mn.u.i; double b=(mx.tag==GT_FLOAT)?mx.u.f:(double)mx.u.i; g_stack[g_sp++]=(GV){GT_KARU,{.k=quanti_prob(rt,dist_uniform(a,b))}}; break;}\n");
        fprintf(f, "  case IR_P_DISCRETE:{\n");
        fprintf(f, "    size_t n=(size_t)in.operand; double *probs=malloc(n*sizeof(double));\n");
        fprintf(f, "    for(size_t i=n;i>0;i--){ GV pv=g_stack[--g_sp]; probs[i-1]=(pv.tag==GT_FLOAT)?pv.u.f:(double)pv.u.i; }\n");
        fprintf(f, "    char **labels=NULL; if(in.aux>=0){ labels=calloc(n,sizeof(char*));\n");
        fprintf(f, "      for(size_t i=0;i<n;i++){ size_t si=(size_t)in.aux+i; labels[i]=strdup(gen_strings[si]); } }\n");
        fprintf(f, "    Distribution *d=dist_discrete(probs,(const char**)labels,n); free(probs);\n");
        fprintf(f, "    if(labels){ for(size_t i=0;i<n;i++) free(labels[i]); free(labels); }\n");
        fprintf(f, "    g_stack[g_sp++]=(GV){GT_KARU,{.k=quanti_prob(rt,d)}}; break;}\n");
        fprintf(f, "  case IR_HALT: ip=sizeof(gen_code)/sizeof(gen_code[0]); break;\n");
        fprintf(f, "  default: break;\n");
        fprintf(f, "  }}\n return 0;}\n");
        fprintf(f, "int main(void){ QuantiRuntime *rt=quanti_init(quanti_default_config()); int rc=gen_run(rt); quanti_destroy(rt); return rc; }\n");
        fclose(f);
        return true;
    }

    fclose(f);
    return true;
}

static void base_name(const char *path, char *out, size_t out_sz) {
    const char *slash = strrchr(path, '/');
    if (!slash) slash = strrchr(path, '\\');
    const char *base = slash ? slash + 1 : path;
    strncpy(out, base, out_sz - 1);
    out[out_sz - 1] = '\0';
    char *dot = strrchr(out, '.');
    if (dot) *dot = '\0';
}

int codegen_build(const char *qa_path, const char *out_exe, bool use_lto) {
    char *source = read_file(qa_path);
    if (!source) return 1;

    Parser p;
    parser_init(&p, source);
    Program prog = parser_parse(&p);
    if (p.had_error) {
        fprintf(stderr, "Parse error: %s\n", p.error_msg);
        free(source);
        program_free(&prog);
        return 1;
    }

    TypeCheckResult tc = typecheck_program(&prog);
    if (tc.had_error) {
        fprintf(stderr, "%s\n", tc.error_msg);
        free(source);
        program_free(&prog);
        return 1;
    }

    IrModule *ir = ir_compile(&prog);
    if (!ir || ir->had_error) {
        if (ir) {
            fprintf(stderr, "%s\n", ir->error_msg);
            ir_free(ir);
        }
        free(source);
        program_free(&prog);
        return 1;
    }

    specialize_module(ir);

    char base[256];
    base_name(qa_path, base, sizeof(base));

#ifdef _WIN32
    system("if not exist build mkdir build");
#else
    system("mkdir -p build");
#endif

    char gen_path[512];
    snprintf(gen_path, sizeof(gen_path), "build/%s_gen.c", base);

    if (!codegen_emit_c(ir, gen_path)) {
        ir_free(ir);
        free(source);
        program_free(&prog);
        return 1;
    }

    char cmd[1024];
    const char *lto_flag = use_lto ? "-flto " : "";
    if (ir->all_classical) {
        /* Pure classical: no libquanti needed */
        snprintf(cmd, sizeof(cmd),
                 "gcc -Wall -Wextra -std=c11 -O2 %s\"%s\" -lm -o \"%s\"",
                 lto_flag, gen_path, out_exe);
    } else {
        snprintf(cmd, sizeof(cmd),
                 "gcc -Wall -Wextra -std=c11 -O2 %s-I include \"%s\" build/libquanti.a -lm -o \"%s\"",
                 lto_flag, gen_path, out_exe);
    }

    int status = system(cmd);
    ir_free(ir);
    free(source);
    program_free(&prog);
    return status != 0 ? status : 0;
}
